POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Bernie Sanders",
    "dateOfBirth": "1850-01-03",
    "gender": "male",
    "occupation": "politician"
}
### Empty req.body test

POST http://localhost:3001/api/patients
Content-Type: application/json

### 

POST http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "type": "HealthCheck",
    "id": "fake id",
    "description": 1,
    "date": true,
    "specialist": true,
    "healthCheckRating": 10
}